"""Read-only sector/company context for a canonical ticker.

Presentation context, nothing else. This module:

* never influences signal generation, qualification, or outcome measurement;
* never gates, filters, ranks, or scores a symbol;
* never decides universe membership — that stays entirely in
  :mod:`core.universe`, which this module does not modify and only consults for
  a company-name fallback;
* never raises for an unknown ticker.

The last property is the important one. Sector data is *optional context*
sitting beside a real trading signal. A missing mapping must degrade to UNKNOWN
and let the signal through, because dropping or failing a signal over absent
display metadata would turn a cosmetic gap into a lost opportunity.

Source: ``data/universe/egx_sector_map.csv``, regenerated by
``scripts/build_egx_sector_map.py``. A missing or malformed map is not fatal —
every lookup simply returns UNKNOWN.
"""

from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path
import threading

from core.universe import canonical, company_name as universe_company_name

#: Additive sector reference. Deliberately NOT ``egx_universe.csv``: membership
#: and sector context are separate concerns with different authorities and
#: different refresh cadences.
SECTOR_MAP_SOURCE = "data/universe/egx_sector_map.csv"

UNKNOWN_SECTOR_ID = "UNKNOWN"
UNKNOWN_SECTOR_NAME = "Unknown"


@dataclass(frozen=True)
class SectorContext:
    """Display context for one ticker. Every numeric field may be ``None``."""

    canonical_ticker: str
    company_name: str
    sector_id: str
    sector_name: str
    sector_rank: int | None
    market_cap_egp: float | None

    @property
    def is_known(self) -> bool:
        return self.sector_id != UNKNOWN_SECTOR_ID

    @property
    def market_cap_billions(self) -> float | None:
        if self.market_cap_egp is None:
            return None
        return self.market_cap_egp / 1_000_000_000


def _optional_int(value):
    try:
        return int(str(value).strip())
    except (TypeError, ValueError):
        return None


def _optional_float(value):
    try:
        return float(str(value).strip())
    except (TypeError, ValueError):
        return None


_CACHE: dict[str, dict[str, SectorContext]] = {}
_LOCK = threading.Lock()


def clear_cache() -> None:
    """Drop the parsed map. Used by tests and after a regeneration."""

    with _LOCK:
        _CACHE.clear()


def _resolve(path=None) -> Path:
    candidate = Path(path or SECTOR_MAP_SOURCE)
    if candidate.is_absolute():
        return candidate
    return Path(__file__).resolve().parent.parent / candidate


def _load(path=None) -> dict[str, SectorContext]:
    resolved = _resolve(path)
    key = str(resolved)
    with _LOCK:
        cached = _CACHE.get(key)
    if cached is not None:
        return cached

    index: dict[str, SectorContext] = {}
    try:
        text = resolved.read_text(encoding="utf-8-sig")
    except OSError:
        # No map on disk is a display gap, not a failure. Everything becomes
        # UNKNOWN and the signal pipeline is unaffected.
        text = ""

    if text:
        for row in csv.DictReader(text.splitlines()):
            ticker = canonical(row.get("canonical_ticker"))
            if not ticker:
                continue
            sector_name = str(row.get("sector_name") or "").strip()
            sector_id = str(row.get("sector_id") or "").strip()
            if not sector_name or not sector_id:
                # A row without a sector carries no context worth indexing;
                # leaving it out makes the ticker resolve to UNKNOWN.
                continue
            index[ticker] = SectorContext(
                canonical_ticker=ticker,
                company_name=str(row.get("company_name") or "").strip(),
                sector_id=sector_id,
                sector_name=sector_name,
                sector_rank=_optional_int(row.get("sector_rank")),
                market_cap_egp=_optional_float(row.get("market_cap_egp")),
            )

    with _LOCK:
        _CACHE[key] = index
    return index


def sector_context(symbol, path=None) -> SectorContext:
    """Context for any accepted ticker spelling. Never raises, never returns None.

    An unmapped ticker still gets a usable record: the company name falls back
    to the canonical universe so a report never shows a bare code, and the
    sector reads UNKNOWN rather than being guessed from a neighbouring row.
    """

    ticker = canonical(symbol)
    if not ticker:
        return SectorContext(
            canonical_ticker="",
            company_name="",
            sector_id=UNKNOWN_SECTOR_ID,
            sector_name=UNKNOWN_SECTOR_NAME,
            sector_rank=None,
            market_cap_egp=None,
        )

    found = _load(path).get(ticker)
    if found is not None:
        if found.company_name:
            return found
        # The map knows the sector but not the name — recover the name without
        # discarding the sector.
        return SectorContext(
            canonical_ticker=ticker,
            company_name=_fallback_company_name(ticker),
            sector_id=found.sector_id,
            sector_name=found.sector_name,
            sector_rank=found.sector_rank,
            market_cap_egp=found.market_cap_egp,
        )

    return SectorContext(
        canonical_ticker=ticker,
        company_name=_fallback_company_name(ticker),
        sector_id=UNKNOWN_SECTOR_ID,
        sector_name=UNKNOWN_SECTOR_NAME,
        sector_rank=None,
        market_cap_egp=None,
    )


def _fallback_company_name(ticker: str) -> str:
    """Company name from the canonical universe, or '' — never a guess."""

    try:
        return universe_company_name(ticker) or ""
    except Exception:
        # core.universe raises UniverseUnavailable when its file is missing.
        # Sector context must not be the thing that breaks a signal display.
        return ""


def sector_map_provenance(path=None) -> dict:
    """Where the loaded map came from, for a status caption."""

    resolved = _resolve(path)
    index = _load(path)
    source = source_as_of = digest = ""
    if index:
        try:
            with open(resolved, encoding="utf-8-sig", newline="") as handle:
                first = next(csv.DictReader(handle), {}) or {}
            source = str(first.get("source") or "")
            source_as_of = str(first.get("source_as_of") or "")
            digest = str(first.get("workbook_sha256") or "")
        except OSError:
            pass
    return {
        "path": str(resolved),
        "available": bool(index),
        "ticker_count": len(index),
        "sector_count": len({record.sector_id for record in index.values()}),
        "source": source,
        "source_as_of": source_as_of,
        "workbook_sha256": digest,
    }
