"""Typed states, provenance constants and honest-naming disclosures.

Every state a symbol can reach is enumerated here so no caller has to compare
free-text strings. Nothing in this module is derived from live Rubix data, a
current incomplete daily candle, or an AI-generated number.
"""

from __future__ import annotations


STRATEGY_NAME = "UPTREND_PULLBACK_SCALPING"
STRATEGY_IDENTITY = "UPTREND_PULLBACK_SCALPING_V1"

EODHD_DAILY = "EODHD_DAILY"

# --- Readiness ---------------------------------------------------------------

SELECTION_READY = "UPTREND_SELECTION_READY"
SELECTION_INSUFFICIENT = "UPTREND_HISTORY_INSUFFICIENT"
SELECTION_UNAVAILABLE = "UPTREND_HISTORY_UNAVAILABLE"
SELECTION_STALE = "UPTREND_HISTORY_STALE"

VOLUME_HISTORY_READY = "VOLUME_HISTORY_READY"
VOLUME_HISTORY_UNRESOLVED = "VOLUME_HISTORY_UNRESOLVED"
VOLUME_HISTORY_UNAVAILABLE = "VOLUME_HISTORY_UNAVAILABLE"

# --- Candidate states --------------------------------------------------------

UPTREND_NEAR_SUPPORT = "UPTREND_NEAR_SUPPORT"
UPTREND_WAIT_FOR_PULLBACK = "UPTREND_WAIT_FOR_PULLBACK"
UPTREND_EXTENDED_NO_CHASE = "UPTREND_EXTENDED_NO_CHASE"
UPTREND_PULLBACK_TOO_DEEP = "UPTREND_PULLBACK_TOO_DEEP"
EMA_ALIGNMENT_FAILED = "EMA_ALIGNMENT_FAILED"
EMA5_SLOPE_FAILED = "EMA5_SLOPE_FAILED"
EMA10_SLOPE_FAILED = "EMA10_SLOPE_FAILED"
TREND_STRUCTURE_FAILED = "TREND_STRUCTURE_FAILED"
SUPPORT_NOT_CONFIRMED = "SUPPORT_NOT_CONFIRMED"
SUPPORT_BROKEN = "SUPPORT_BROKEN"
INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"
INSUFFICIENT_LIQUIDITY = "INSUFFICIENT_LIQUIDITY"
DATA_UNAVAILABLE = "DATA_UNAVAILABLE"
PROVENANCE_REJECTED = "PROVENANCE_REJECTED"

CANDIDATE_STATES = (
    UPTREND_NEAR_SUPPORT,
    UPTREND_WAIT_FOR_PULLBACK,
    UPTREND_EXTENDED_NO_CHASE,
    UPTREND_PULLBACK_TOO_DEEP,
    EMA_ALIGNMENT_FAILED,
    EMA5_SLOPE_FAILED,
    EMA10_SLOPE_FAILED,
    TREND_STRUCTURE_FAILED,
    SUPPORT_NOT_CONFIRMED,
    SUPPORT_BROKEN,
    INSUFFICIENT_HISTORY,
    INSUFFICIENT_LIQUIDITY,
    DATA_UNAVAILABLE,
    PROVENANCE_REJECTED,
)

# Hard-gate states are resolved in this order, so the first failing gate is the
# reported state even when several fail together.
BLOCKING_STATE_ORDER = (
    DATA_UNAVAILABLE,
    PROVENANCE_REJECTED,
    INSUFFICIENT_HISTORY,
    INSUFFICIENT_LIQUIDITY,
    EMA_ALIGNMENT_FAILED,
    EMA5_SLOPE_FAILED,
    EMA10_SLOPE_FAILED,
    TREND_STRUCTURE_FAILED,
    SUPPORT_NOT_CONFIRMED,
    SUPPORT_BROKEN,
    UPTREND_PULLBACK_TOO_DEEP,
)

# --- Support zone source types ----------------------------------------------

SUPPORT_SOURCE_EMA10 = "EMA10_AREA"
SUPPORT_SOURCE_SWING_LOW = "CONFIRMED_DAILY_SWING_LOW"
SUPPORT_SOURCE_CONSOLIDATION = "PRIOR_CONSOLIDATION_LEVEL"
SUPPORT_SOURCE_BREAKOUT = "PRIOR_BREAKOUT_LEVEL"

SUPPORT_SOURCE_TYPES = (
    SUPPORT_SOURCE_EMA10,
    SUPPORT_SOURCE_SWING_LOW,
    SUPPORT_SOURCE_CONSOLIDATION,
    SUPPORT_SOURCE_BREAKOUT,
)

# --- Deterministic reason codes ---------------------------------------------

REASON_EMA_ALIGNMENT = "EMA5_NOT_ABOVE_EMA10"
REASON_EMA5_SLOPE = "EMA5_SLOPE_BELOW_MINIMUM"
REASON_EMA10_SLOPE = "EMA10_SLOPE_BELOW_MINIMUM"
REASON_CLOSE_BELOW_EMA10 = "RECENT_CLOSES_STRUCTURALLY_BELOW_EMA10"
REASON_LAST_CLOSE_BELOW_EMA10 = "LAST_CLOSE_STRUCTURALLY_BELOW_EMA10"
REASON_TREND_TOO_YOUNG = "TREND_SESSIONS_BELOW_MINIMUM"
REASON_DESCENDING_HIGHS = "RECENT_SWING_HIGHS_DESCENDING"
REASON_DESCENDING_LOWS = "RECENT_SWING_LOWS_DESCENDING"
REASON_NO_STRUCTURE_PIVOTS = "INSUFFICIENT_CONFIRMED_SWING_PIVOTS"
REASON_SUPPORT_NO_SOURCES = "SUPPORT_SOURCE_COUNT_BELOW_MINIMUM"
REASON_SUPPORT_NO_TOUCHES = "SUPPORT_TOUCH_PROXY_COUNT_BELOW_MINIMUM"
REASON_SUPPORT_WEAK = "SUPPORT_STRENGTH_BELOW_MINIMUM"
REASON_SUPPORT_ZONE_TOO_WIDE = "SUPPORT_ZONE_WIDER_THAN_MAXIMUM"
REASON_SUPPORT_ABOVE_PRICE = "NO_SUPPORT_LEVEL_BELOW_LAST_CLOSE"
REASON_SUPPORT_INVALIDATED = "CLOSE_BELOW_SUPPORT_INVALIDATION_LEVEL"
REASON_PULLBACK_TOO_DEEP = "PULLBACK_DEPTH_ABOVE_MAXIMUM"
REASON_EXTENDED = "DISTANCE_FROM_SUPPORT_ABOVE_NO_CHASE_LIMIT"
REASON_WAIT_FOR_PULLBACK = "DISTANCE_FROM_SUPPORT_ABOVE_NEAR_SUPPORT_BAND"
REASON_TURNOVER_BELOW_MINIMUM = "MEDIAN_TURNOVER_BELOW_MINIMUM"
REASON_VOLUME_BELOW_MINIMUM = "MEDIAN_VOLUME_BELOW_MINIMUM"
REASON_VOLUME_HISTORY_UNRESOLVED = VOLUME_HISTORY_UNRESOLVED
REASON_STALE_HISTORY = "LATEST_SESSION_TOO_FAR_BEFORE_CUTOFF"
REASON_STATE_NOT_ELIGIBLE = "CANDIDATE_STATE_NOT_IN_ELIGIBLE_SET"

REASON_TREND_CONFIRMED = "SHORT_TERM_UPTREND_CONFIRMED"
REASON_SUPPORT_CONFIRMED = "SUPPORT_ZONE_CONFLUENCE_CONFIRMED"
REASON_NEAR_SUPPORT = "PRICE_INSIDE_NEAR_SUPPORT_BAND"

# --- Honest-naming disclosures ----------------------------------------------

DAILY_PATH_DISCLOSURE = (
    "Daily OHLC does not reveal whether the session high or low occurred "
    "first; no first-touch target/stop claim is made."
)
DAILY_AUCTION_DISCLOSURE = (
    "Daily historical metrics may include official closing-auction effects. "
    "Continuous-session-only historical enrichment is not available."
)
SUPPORT_PROXY_DISCLOSURE = (
    "Support touches and reactions are daily-bar proxies. Intraday reaction "
    "at the level is not observable from completed daily candles."
)
RESEARCH_ONLY_DISCLOSURE = (
    "Research zones only. This selector never places, sizes, or schedules an "
    "order."
)

FIRST_TOUCH_ORDER_AVAILABLE = False
